//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BorrowedItem", Namespace="http://schemas.datacontract.org/2004/07/LibraryService")]
    [System.SerializableAttribute()]
    public partial class BorrowedItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference1.Book BookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BorrowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference1.Book Book {
            get {
                return this.BookField;
            }
            set {
                if ((object.ReferenceEquals(this.BookField, value) != true)) {
                    this.BookField = value;
                    this.RaisePropertyChanged("Book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/LibraryService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoSuchBookException", Namespace="http://schemas.datacontract.org/2004/07/LibraryService.Exceptions")]
    [System.SerializableAttribute()]
    public partial class NoSuchBookException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILibrary")]
    public interface ILibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/ListOfBorrowedItems", ReplyAction="http://tempuri.org/ILibrary/ListOfBorrowedItemsResponse")]
        Client.ServiceReference1.BorrowedItem[] ListOfBorrowedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/ListOfBorrowedItems", ReplyAction="http://tempuri.org/ILibrary/ListOfBorrowedItemsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.BorrowedItem[]> ListOfBorrowedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetBorrowedBooks", ReplyAction="http://tempuri.org/ILibrary/GetBorrowedBooksResponse")]
        Client.ServiceReference1.Book[] GetBorrowedBooks(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetBorrowedBooks", ReplyAction="http://tempuri.org/ILibrary/GetBorrowedBooksResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Book[]> GetBorrowedBooksAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/BookInfo", ReplyAction="http://tempuri.org/ILibrary/BookInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.NoSuchBookException), Action="http://tempuri.org/ILibrary/BookInfoNoSuchBookExceptionFault", Name="NoSuchBookException", Namespace="http://schemas.datacontract.org/2004/07/LibraryService.Exceptions")]
        Client.ServiceReference1.Book BookInfo(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/BookInfo", ReplyAction="http://tempuri.org/ILibrary/BookInfoResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Book> BookInfoAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/BorrowBook", ReplyAction="http://tempuri.org/ILibrary/BorrowBookResponse")]
        bool BorrowBook(int bookId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/BorrowBook", ReplyAction="http://tempuri.org/ILibrary/BorrowBookResponse")]
        System.Threading.Tasks.Task<bool> BorrowBookAsync(int bookId, int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryChannel : Client.ServiceReference1.ILibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ILibrary>, Client.ServiceReference1.ILibrary {
        
        public LibraryClient() {
        }
        
        public LibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference1.BorrowedItem[] ListOfBorrowedItems() {
            return base.Channel.ListOfBorrowedItems();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.BorrowedItem[]> ListOfBorrowedItemsAsync() {
            return base.Channel.ListOfBorrowedItemsAsync();
        }
        
        public Client.ServiceReference1.Book[] GetBorrowedBooks(int userId) {
            return base.Channel.GetBorrowedBooks(userId);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Book[]> GetBorrowedBooksAsync(int userId) {
            return base.Channel.GetBorrowedBooksAsync(userId);
        }
        
        public Client.ServiceReference1.Book BookInfo(int bookId) {
            return base.Channel.BookInfo(bookId);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Book> BookInfoAsync(int bookId) {
            return base.Channel.BookInfoAsync(bookId);
        }
        
        public bool BorrowBook(int bookId, int userId) {
            return base.Channel.BorrowBook(bookId, userId);
        }
        
        public System.Threading.Tasks.Task<bool> BorrowBookAsync(int bookId, int userId) {
            return base.Channel.BorrowBookAsync(bookId, userId);
        }
    }
}
